# Generated by Django 5.2.4 on 2025-08-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='user_messages.usermessages', verbose_name='Conversation'),
        ),
    ]
