# Generated by Django 5.0.11 on 2025-07-04 10:42

import apps.vehicles.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.PositiveIntegerField(help_text='Production year (1900–next year)', validators=[apps.vehicles.models.max_year_validator], verbose_name='Year')),
                ('price', models.DecimalField(decimal_places=2, help_text='Positive price only', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage')),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('other', 'Other')], max_length=30, null=True, verbose_name='Color')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Engine volume (L)')),
                ('engine_power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine power (hp)')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('gas', 'Gas'), ('other', 'Other')], max_length=20, null=True, verbose_name='Fuel type')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('robotic', 'Robotic'), ('other', 'Other')], max_length=20, null=True, verbose_name='Transmission')),
                ('registration_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration country')),
                ('is_custom_cleared', models.BooleanField(blank=True, null=True, verbose_name='Customs cleared')),
                ('vin_code', models.CharField(blank=True, help_text='Unique VIN code (may be empty)', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid VIN', regex='^[A-HJ-NPR-Z0-9]{11,17}$')], verbose_name='VIN code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='View count')),
                ('number_of_owners', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of owners')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(help_text='User who created the vehicle listing', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='AirTransport',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('aircraft_type', models.CharField(max_length=50, verbose_name='Aircraft type')),
                ('engine_count', models.PositiveIntegerField(verbose_name='Engine count')),
                ('max_altitude', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max altitude (m)')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('seats', models.PositiveIntegerField(verbose_name='Number of seats')),
                ('doors_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of doors')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('body_type', models.CharField(max_length=30, verbose_name='Body type')),
                ('drive_type', models.CharField(max_length=20, verbose_name='Drive type')),
                ('technical_condition', models.TextField(blank=True, null=True, verbose_name='Technical condition')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('bike_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bike type')),
                ('seat_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seat height (mm)')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='Motorhome',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('sleeping_places', models.PositiveIntegerField(verbose_name='Sleeping places')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='Has kitchen')),
                ('has_bathroom', models.BooleanField(default=False, verbose_name='Has bathroom')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='SpecialTech',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('specialization', models.CharField(max_length=50, verbose_name='Specialization')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (kg)')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('trailer_type', models.CharField(max_length=30, verbose_name='Trailer type')),
                ('load_capacity', models.PositiveIntegerField(verbose_name='Load capacity (kg)')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('load_capacity', models.PositiveIntegerField(verbose_name='Load capacity (kg)')),
                ('axle_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Axle count')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='WaterTransport',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('boat_type', models.CharField(max_length=50, verbose_name='Boat type')),
                ('engine_type', models.CharField(max_length=50, verbose_name='Engine type')),
                ('hull_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hull material')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='Vehicle')),
            ],
        ),
    ]
