# Generated by Django 5.0.11 on 2025-09-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('trailer', 'Trailer'), ('specialtech', 'Special Tech'), ('bus', 'Bus'), ('watertransport', 'Water Transport'), ('airtransport', 'Air Transport'), ('motorhome', 'Motorhome')], default='car', help_text='Type of vehicle', max_length=20, verbose_name='Vehicle Type'),
        ),
    ]
