# Generated by Django 5.0.11 on 2025-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Is vehicle new or used', verbose_name='Is New'),
        ),
    ]
